begin reformatting std files

diff --git a/src/parse b/src/parse
--- a/src/parse
+++ b/src/parse
@@ -7,10 +7,11 @@ JACKSON_CORE="${LIBPLCC_LIB}/lib/jackson/jackson-core-${JACKSON_VERSION}.jar"
 JACKSON_DATABIND="${LIBPLCC_LIB}/lib/jackson/jackson-databind-${JACKSON_VERSION}.jar"
 CP="${JACKSON_ANNOTATIONS}:${JACKSON_CORE}:${JACKSON_DATABIND}"
 
-[ -d Java ] || {
-    echo "Java directory missing" >&2
+if [ ! -d Java ] && [ ! -d Python ];
+then
+    echo "Source file directory missing" >&2
     exit 1
-}
+fi
 
 [ -f Java/Parse.class ] || {
     echo "Java/Parse.class missing" >&2
